# Generated by Django 4.2.4 on 2023-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tb_registros_data_da_ocorrência_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_registros',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações'),
        ),
    ]
